Repository frenck/python-peblar, pull requests merged in 2024-12, with the labels that each got.

#5 Update `version` command documentation
  src/peblar/cli/__init__.py
Labels: documentation

#6 Fix total current in CLI returning 10 times to much current
  src/peblar/cli/__init__.py
Labels: bugfix

#12 Export all models in package root
  src/peblar/__init__.py
Labels: enhancement

#17 Fix flaky voltage, add current total
  src/peblar/models.py
Labels: bugfix, new-feature
